### ISSUE TITLE
Error downloading subtitles

### ISSUE THREAD

**Issue by gabri94** [jellyfin/jellyfin-plugin-opensubtitles#47] opened 2021-04-14 11:02 UTC
Hi, since a few days I'm unable to download subtitles.

```[2021-04-14 13:01:06.906 +02:00] [ERR] Error downloading subtitles from "Open Subtitles"
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at XmlRpcHandler.XmlRpcGenerator.DecodeMethodResponse(String xmlResponse)
   at OpenSubtitlesHandler.OpenSubtitles.LogInAsync(String username, String password, String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Login(CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.<>c__DisplayClass11_0.<<SearchSubtitles>b__3>d.MoveNext()```

**Comment by fatraaij** [comment] 2021-05-24 23:15
This is probably a duplicate of #41

**Comment by zjeffer** [comment] 2021-05-25 17:43
@gabri94 Can you close this issue? Just to prevent clutter :)

**Closed** 2021-05-25 18:53 UTC
