### ISSUE TITLE
V7 Won't download

### ISSUE THREAD

**Issue by PhieF** [jellyfin/jellyfin-plugin-opensubtitles#17] opened 2019-10-31 21:38 UTC
Hi,

First, thanks for your work :)

The last version of the plugin won't be activated:
I hit download on jellyfin, it asks me to restart the server, that I do, then the extension isn't there.
I install the v6, and it works

Any ideas why ?

Thanks

**Comment by cryptobank** [comment] 2019-11-01 07:30
Same issue.

**Comment by anthonylavado** [comment] 2019-11-01 16:38
@PhieF @cryptobank Are you on Windows?

There’s a known issue right now where we can’t upgrade plugins on Windows, so you’d have to:
* Stop Jellyfin
* Find the plugin in the folder
* Delete it (but leave the configuration file)
* Start Jellyfin, install plugin

**Comment by cryptobank** [comment] 2019-11-01 18:05
I’m on Debian .(openmediavault)

**Comment by PhieF** [comment] 2019-11-01 20:54
Ubuntu here, I will try your work around but v6 works

**Comment by anthonylavado** [comment] 2019-11-01 21:22
Yeah, you could still try this workaround on Debian/Ubuntu. I'll test the upgrade path tonight to make sure there's nothing else going on.

**Comment by Rijul-Ahuja** [comment] 2019-11-01 22:17
I tried the workaround by deleting `/var/lib/jellyfin/plugins/Open Subtitles` but it did not work

**Comment by joshuaboniface** [comment] 2019-11-03 20:46
It looks like this was an intermittent build failure, but the automation didn't fail the build, and hence we got a zip with a missing .DLL.

Working around this now, then will trigger a new build.

**Comment by joshuaboniface** [comment] 2019-11-03 21:52
This has been rebuilt as v7. The downside is, this pulled the NuGet packages for 10.4.1 instead of 10.4.0, so this needs 10.4.1 now. I've updated the manifest manually to reflect this for now until the next version.

**Comment by dkanada** [comment] 2019-11-04 11:04
The fix was confirmed in another issue report so I will close this instance, let us know if you still have issues with the new version.

**Closed** 2019-11-04 11:04 UTC
